services:
  frontend:
    build: ./client
    container_name: frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
  backend:
    build: ./server
    container_name: backend
    ports:
      - '8080:8080'
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    env_file: ./server/.env
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    restart: always
